author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /ReaduxIoExport_QuintiHoratii_Annotated30
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - openseadragon.min.js
    - openseadragon-svg-overlay.js
    - text-annotations.js
    - viewer.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://iiif.archivelab.org/iiif//03291785.4943.emory.edu$1/full/full/0/default.jpg
image_size:
  page:
    height: 1785
    width: 2325
permalink: pretty
publication_info:
  date: '2023'
  editors: []
  title: Quinti Horatii Flacci emblemata imaginibus in aes incisis, notisq[ue] illustrata
show_annotation_author: true
source_info:
  title: Quinti Horatii Flacci emblemata imaginibus in aes incisis, notisq[ue] illustrata
  via_readux: true
tagline: an annotated digital edition
title: Quinti Horatii Flacci emblemata imaginibus in aes incisis, notisq[ue] illustrata
url: https://jcmundy.github.io
version: 0.7
